services:
  mysql:
    build: ./db
    container_name: mysql-respres
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s

  api:
    build: ./api
    container_name: laravel_api
    ports:
      - "5000:80"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api:/var/www/html
      - ./api/.env.example:/var/www/html/.env
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge