services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql-respres
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: resPre
      MYSQL_USER: user
      MYSQL_PASSWORD: userPass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s

  api:
    build: ./api
    container_name: laravel_api
    ports:
      - "5000:80"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api:/var/www/html
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge