services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql-respres
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: resPre
      MYSQL_USER: user
      MYSQL_PASSWORD: userPass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s

  mysqld-exporter:
    image: prom/mysqld-exporter:v0.15.0
    container_name: mysqld-exporter
    environment:
      MYSQLD_EXPORTER_PASSWORD: userPass
    command:
      - "--collect.info_schema.tables"
      - "--collect.info_schema.innodb_metrics"
      - "--collect.perf_schema.tablelocks"
      - "--mysqld.username=user"
      - "--mysqld.address=mysql:3306"
    ports:
      - "9104:9104"
    networks:
      - app-network
    depends_on:
      - mysql

  redis:
    image: redis:7.4.3
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: "redis:6379"
    networks:
      - app-network
    depends_on:
      - redis

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
      args:
        APACHE_DOCUMENT_ROOT: /var/www/html/public
        SERVERNAME: localhost
    container_name: laravel
    ports:
      - "5000:80"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge