services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql-respres
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: resPre
      MYSQL_USER: user
      MYSQL_PASSWORD: userPass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build: ./api
    container_name: laravel_api
    ports:
      - "5000:80"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./api:/var/www/html
      - ./api/.env.development:/var/www/html/.env
    networks:
      - app-network


  frontend:
    build: ./front
    container_name: webpack_frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - api

volumes:
  mysql_data:
  redis_data:

networks:
  app-network:
    driver: bridge