services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: resPre
      MYSQL_USER: user
      MYSQL_PASSWORD: userPass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 45s

  api:
    build: ./api
    container_name: laravel_api
    ports:
      - "5000:80"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: resPre
      DB_USERNAME: user
      DB_PASSWORD: userPass
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api:/var/www/html

  frontend:
    build: ./front
    container_name: js_frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  mysql_data:
