services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: resPre
      MYSQL_USER: user
      MYSQL_PASSWORD: userPass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:
