<?php

namespace Database\Seeders;

use App\Models\ConflictTest;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ConflictTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ConflictTest::makeMany([
            [
                'name' => '1945 Khuzestan revolt',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1945',
                'end_date_accuracy' => '',
                'end_date' => '1949',
                'is_active' => false,
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => null,
            ],
            [
                'name' => 'Crusader insurgency',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Crusaders_(guerrilla)',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1945',
                'end_date_accuracy' => '',
                'end_date' => '1950',
                'is_active' => false,
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => true,
            ],
            [
                'name' => 'Chinese Civil War',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Chinese_Civil_War',
                'location' => 'Mainland China',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Mainland_China',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1927-08-01',
                'end_date_accuracy' => '',
                'end_date' => '1945-08-10',
                'is_active' => false,
                'casualties_low' => 9500000,
                'casualties_hig' => 13000000,
                'description_complete' => true,
            ],
            [
                'name' => 'August Revolution',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/August_Revolution',
                'location' => 'Empire of Vietnam',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Empire_of_Vietnam',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => false,
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => false,
            ],
            [
                'name' => 'Indonesian National Revolution',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Indonesian_National_Revolution',
                'location' => 'Dutch East Indies',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Dutch_East_Indies',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1945-08-17',
                'end_date_accuracy' => '',
                'end_date' => '1949-12-27',
                'is_active' => false,
                'casualties_low' => 2244799,
                'casualties_hig' => 2262299,
                'description_complete' => true,
            ],
            [
                'name' => 'Korean conflict',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Korean_conflict',
                'location' => 'Korea',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Korea',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1948-09-01',
                'end_date_accuracy' => '',
                'end_date' => '2025-05-12',
                'is_active' => true,
                'casualties_low' => 4140968,
                'casualties_hig' => 5540968,
                'description_complete' => '',
            ],
            [
                'name' => 'War in Vietnam (1945–1946)',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/War_in_Vietnam_(1945%E2%80%931946)',
                'location' => 'South Vietnam below the 16th parallel',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1945-09-23',
                'end_date_accuracy' => '1946-03-30',
                'end_date' => '',
                'is_active' => false,
                'casualties_low' => 2740,
                'casualties_hig' => 2740,
                'description_complete' => '',
            ],
            [
                'name' => '1945 Hazara Rebellion',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/1945_Hazara_Rebellion',
                'location' => 'Kingdom of Afghanistan',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Kingdom_of_Afghanistan',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1945-11-01',
                'end_date_accuracy' => '',
                'end_date' => '1946-03-01',
                'is_active' => false,
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
            [
                'name' => 'Iran crisis of 1946',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Iran_crisis_of_1946',
                'location' => 'Iran',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Iran',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1945-11-01',
                'end_date_accuracy' => '',
                'end_date' => '1946-12-15',
                'is_active' => false,
                'casualties_low' => 2000,
                'casualties_hig' => 2000,
                'description_complete' => '',
            ],
            [
                'name' => 'Greek Civil War',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Greek_Civil_War',
                'location' => 'Greece',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Greece',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1946-03-31',
                'end_date_accuracy' => '',
                'end_date' => '1949-08-30',
                'is_active' => false,
                'casualties_low' => 80000,
                'casualties_hig' => 158000,
                'description_complete' => '',
            ],
            [
                'name' => 'Hukbalahap rebellion',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Hukbalahap_rebellion',
                'location' => 'Central Luzon',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Central_Luzon',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1946-07-04',
                'end_date_accuracy' => '',
                'end_date' => '1954-05-17',
                'is_active' => false,
                'casualties_low' => 11300,
                'casualties_hig' => 11300,
                'description_complete' => '',
            ],
            [
                'name' => 'Autumn Uprising of 1946',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Autumn_Uprising_of_1946',
                'location' => 'South Korea',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/South_Korea',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1946-09-22',
                'end_date_accuracy' => '',
                'end_date' => '1946-12-20',
                'is_active' => false,
                'casualties_low' => 611,
                'casualties_hig' => 611,
                'description_complete' => '',
            ],
            [
                'name' => 'Corfu Channel incident',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Corfu_Channel_incident',
                'location' => 'Straits of Corfu',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Straits_of_Corfu',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1946-05-15',
                'end_date_accuracy' => '',
                'end_date' => '1946-11-13',
                'is_active' => false,
                'casualties_low' => 44,
                'casualties_hig' => 44,
                'description_complete' => '',
            ],
            [
                'name' => 'Punnapra-Vayalar uprising',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Punnapra-Vayalar_uprising',
                'location' => 'Punnapra and Vayalar',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Vayalar',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1946-10-01',
                'end_date_accuracy' => '',
                'end_date' => '1946-10-31',
                'is_active' => false,
                'casualties_low' => 1040,
                'casualties_hig' => 1040,
                'description_complete' => '',
            ],
            [
                'name' => 'First Indochina War',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/First_Indochina_War',
                'location' => 'French Indochina',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/French_Indochina',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1946-12-19',
                'end_date_accuracy' => '',
                'end_date' => '1954-07-21',
                'is_active' => false,
                'casualties_low' => 525000,
                'casualties_hig' => 1242707,
                'description_complete' => '',
            ],
            [
                'name' => 'Paraguayan Civil War (1947)',
                'conflict_wiki_url' => 'https://en.wikipedia.org/wiki/Paraguayan_Civil_War_(1947)',
                'location' => 'Paraguay',
                'location_wiki_url' => 'https://en.wikipedia.org/wiki/Paraguay',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '1947-03-07',
                'end_date_accuracy' => '',
                'end_date' => '1947-08-20',
                'is_active' => false,
                'casualties_low' => 4000,
                'casualties_hig' => 4000,
                'description_complete' => '',
            ],
            [
                'name' => '',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => '',
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
            [
                'name' => '',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => '',
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
            [
                'name' => '',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => '',
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
            [
                'name' => '',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => '',
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
            [
                'name' => '',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => '',
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
            [
                'name' => '',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => '',
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
            [
                'name' => '',
                'conflict_wiki_url' => '',
                'location' => '',
                'location_wiki_url' => '',
                'side_a_other_sides' => '',
                'side_b_other_sides' => '',
                'start_date_accuracy' => '',
                'start_date' => '',
                'end_date_accuracy' => '',
                'end_date' => '',
                'is_active' => '',
                'casualties_low' => 0,
                'casualties_hig' => 0,
                'description_complete' => '',
            ],
        ])->saveMany();
    }
}
